name: workspace-esm
channels:
  - biocore
  - pytorch
  - nvidia
  - schrodinger
  - conda-forge
  - https://conda.anaconda.org/domdfcoding
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _sysroot_linux-64_curr_repodata_hack=3
  - apbs=1.5
  - biopython=1.83
  - blas=1.0
  - blosc=1.21.5
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.7.4
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2024.7.4
  - charset-normalizer=2.0.4
  - collada2gltf=2.1.4
  - contourpy=1.2.1
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-opencl=12.4.127
  - cuda-runtime=11.8.0
  - cycler=0.12.1
  - dbus=1.13.18
  - dm-tree=0.1.7
  - einops=0.8.0
  - expat=2.6.2
  - ffmpeg=4.3
  - filelock=3.13.1
  - fontconfig=2.14.2
  - fonttools=4.53.0
  - freetype=2.12.1
  - glew=2.1.0
  - glib=2.80.2
  - glib-tools=2.80.2
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h5py=3.11.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - hmmer=3.1b2
  - huggingface_hub=0.23.4
  - icu=73.2
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libaec=1.1.3
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang13=14.0.6
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.9.1.3
  - libcups=2.3.3
  - libcurand=10.3.5.147
  - libcurl=8.7.1
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.17
  - libdrm-cos7-x86_64=2.4.97
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.6.2
  - libffi=3.4.4
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.80.2
  - libglu=9.0.0
  - libglvnd-cos7-x86_64=1.0.1
  - libglvnd-glx-cos7-x86_64=1.0.1
  - libgomp=13.2.0
  - libholoplaycore=0.1.0_rc4
  - libiconv=1.17
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnetcdf=4.9.2
  - libnghttp2=1.58.0
  - libnpp=11.8.0.86
  - libnsl=2.0.1
  - libnvjitlink=12.1.105
  - libnvjpeg=11.9.0.86
  - libopenblas=0.3.27
  - libpng=1.6.39
  - libpq=12.17
  - libsqlite=3.45.3
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxkbcommon=1.6.0
  - libxml2=2.11.6
  - libzip=1.10.1
  - libzlib=1.2.13
  - lightning=2.3.3
  - lightning-utilities=0.11.5
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - mengine=1
  - mesa-libgl-cos7-x86_64=18.3.4
  - mesa-libglapi-cos7-x86_64=18.3.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mmcif_pdbx=2.0.1
  - mpc=1.1.0
  - mpeg_encode=1
  - mpfr=4.0.2
  - mpmath=1.3.0
  - mtz2ccp4_px=1.1
  - munkres=1.1.4
  - mysql=5.7.20
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.2.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.3.1
  - packaging=24.0
  - pandas=2.2.2
  - pcre2=10.43
  - pdb2pqr=3.6.1
  - pillow=10.3.0
  - pip=24.0
  - pmw=2.0.1
  - propka=3.5.1
  - pthread-stubs=0.4
  - pycollada=0.8
  - pykerberos=1.2.4
  - pymol=3.0.3
  - pymol-bundle=3.0.2
  - pymol-web-examples=2.4
  - pyparsing=3.1.2
  - pyqt=5.15.4
  - pyqt5-sip=12.9.0
  - pysocks=1.7.1
  - python=3.10.13
  - python-dateutil=2.9.0
  - python-tzdata=2024.1
  - python_abi=3.10
  - pytorch=2.3.1
  - pytorch-cuda=11.8
  - pytorch-lightning=2.3.3
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.1
  - qt-main=5.15.2
  - readline=8.2
  - requests=2.31.0
  - rigimol=1.3
  - scipy=1.13.1
  - setuptools=69.5.1
  - sip=6.5.1
  - six=1.16.0
  - snappy=1.2.0
  - sqlite=3.45.3
  - sympy=1.12
  - sysroot_linux-64=2.17
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - toml=0.10.2
  - torchaudio=2.3.1
  - torchmetrics=1.4.0.post0
  - torchtriton=2.3.1
  - torchvision=0.18.1
  - tornado=6.4
  - tqdm=4.66.4
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024a
  - unicodedata2=15.1.0
  - urllib3=2.2.1
  - vtk-m=1.8.0
  - wheel=0.43.0
  - xkeyboard-config=2.41
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.5
      - aiosignal==1.3.1
      - alembic==1.13.2
      - aniso8601==9.0.1
      - anyio==4.3.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - astunparse==1.6.3
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attr==0.3.2
      - attrs==23.2.0
      - babel==2.15.0
      - beautifulsoup4==4.12.3
      - biotite==0.41.2
      - bleach==6.1.0
      - blinker==1.8.2
      - blosum==2.0.3
      - cachetools==5.5.0
      - cffi==1.16.0
      - click==8.1.7
      - cloudpickle==3.0.0
      - comm==0.2.2
      - contextlib2==21.6.0
      - databricks-sdk==0.31.1
      - debugpy==1.8.1
      - decorator==5.1.1
      - defusedxml==0.7.1
      - deprecated==1.2.14
      - docker==7.1.0
      - evodiff==1.1.0
      - exceptiongroup==1.2.1
      - executing==2.0.1
      - fair-esm==2.0.0
      - fasteners==0.19
      - fastjsonschema==2.19.1
      - flask==3.0.3
      - flatbuffers==24.3.25
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2024.5.0
      - gast==0.6.0
      - generate-chroma==1.0.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-auth==2.34.0
      - google-pasta==0.2.0
      - graphene==3.3
      - graphql-core==3.2.3
      - graphql-relay==3.2.0
      - greenlet==3.0.3
      - griddataformats==1.0.2
      - grpcio==1.64.1
      - gunicorn==23.0.0
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.23.1
      - importlib-metadata==8.4.0
      - iniconfig==2.0.0
      - ipykernel==6.29.4
      - ipython==8.24.0
      - ipywidgets==8.1.2
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jedi==0.19.1
      - json5==0.9.25
      - jsonpointer==2.4
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.2
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.1
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.2
      - jupyterlab-widgets==3.0.10
      - keras==3.4.1
      - libclang==18.1.1
      - lmdb==1.5.1
      - mako==1.3.5
      - markdown==3.6
      - markdown-it-py==3.0.0
      - matplotlib-inline==0.1.7
      - mda-xdrlib==0.2.0
      - mdanalysis==2.7.0
      - mdurl==0.1.2
      - mistune==3.0.2
      - ml-collections==0.1.1
      - ml-dtypes==0.3.2
      - mlflow==2.16.0
      - mlflow-skinny==2.16.0
      - mmtf-python==1.1.3
      - mrcfile==1.5.3
      - msgpack==1.0.8
      - msgpack-numpy==0.4.8
      - multidict==6.0.5
      - namex==0.0.8
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - nglview==3.1.2
      - notebook==7.2.0
      - notebook-shim==0.2.4
      - opentelemetry-api==1.27.0
      - opentelemetry-sdk==1.27.0
      - opentelemetry-semantic-conventions==0.48b0
      - opt-einsum==3.3.0
      - optree==0.11.0
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pdb-tools==2.5.0
      - pexpect==4.9.0
      - platformdirs==4.2.2
      - pluggy==1.5.0
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.43
      - protobuf==4.25.3
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==17.0.0
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pycparser==2.22
      - pyg-lib==0.4.0+pt23cu118
      - pygments==2.18.0
      - pytest==8.2.1
      - python-json-logger==2.0.7
      - pyzmq==26.0.3
      - referencing==0.35.1
      - regex==2024.5.15
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.7.1
      - rpds-py==0.18.1
      - rsa==4.9
      - scikit-learn==1.1.2
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sequence-models==1.8.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - soupsieve==2.5
      - sqlalchemy==2.0.32
      - sqlparse==0.5.1
      - stack-data==0.6.3
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.16.2
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==2.4.0
      - terminado==0.18.1
      - tinycss2==1.3.0
      - tokenizers==0.13.3
      - tomli==2.0.1
      - torch-cluster==1.6.3+pt23cu118
      - torch-geometric==2.5.3
      - torch-scatter==2.1.2+pt23cu118
      - torch-sparse==0.6.18+pt23cu118
      - torch-spline-conv==1.2.2+pt23cu118
      - torchtext==0.18.0
      - traitlets==5.14.3
      - transformers==4.24.0
      - types-python-dateutil==2.9.0.20240316
      - uri-template==1.3.0
      - wcwidth==0.2.13
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.0.3
      - widgetsnbextension==4.0.10
      - wrapt==1.16.0
      - yarl==1.9.7
      - zipp==3.20.1
